// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHlcP7buGDVidpb3LOX48BHPSFJurS7DU',
    appId: '1:111884327724:web:d39c8cac391f82a7b7aa89',
    messagingSenderId: '111884327724',
    projectId: 'missionforce-81570',
    authDomain: 'missionforce-81570.firebaseapp.com',
    storageBucket: 'missionforce-81570.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavSKYOuQhRYHCGDlydjoKRQaJ0esmV_Q',
    appId: '1:111884327724:android:018d4c87d0a6a152b7aa89',
    messagingSenderId: '111884327724',
    projectId: 'missionforce-81570',
    storageBucket: 'missionforce-81570.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzFghGFSq5hosJr0DkJY6J_T26cOUD1o',
    appId: '1:111884327724:ios:4bb411b9d9f0dff0b7aa89',
    messagingSenderId: '111884327724',
    projectId: 'missionforce-81570',
    storageBucket: 'missionforce-81570.firebasestorage.app',
    iosBundleId: 'com.example.missionForce',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChzFghGFSq5hosJr0DkJY6J_T26cOUD1o',
    appId: '1:111884327724:ios:4bb411b9d9f0dff0b7aa89',
    messagingSenderId: '111884327724',
    projectId: 'missionforce-81570',
    storageBucket: 'missionforce-81570.firebasestorage.app',
    iosBundleId: 'com.example.missionForce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHlcP7buGDVidpb3LOX48BHPSFJurS7DU',
    appId: '1:111884327724:web:feb81bb7d406c52fb7aa89',
    messagingSenderId: '111884327724',
    projectId: 'missionforce-81570',
    authDomain: 'missionforce-81570.firebaseapp.com',
    storageBucket: 'missionforce-81570.firebasestorage.app',
  );
}
